### ISSUE TITLE
Can you give me some intution about what the weight argument is for? 

### ISSUE THREAD

**Issue by sg-s** [garydoranjr/pyemd#8]
If i would hazard a guess, it would be useful if my histogram has non-equal bin sizes. Am I right?

**Comment by garydoranjr** [comment]
@sg-s, the `emd` function does not assume the data is already in histogram form; it will compute the EMD between two arbitrary n-dimensional samples. If you already have a histogram representation, then you can use the histogram bin centers as the points in the sample, and in that case the weights would correspond to the probability mass within each histogram bin (i.e. the fraction of samples falling within that bin).

More generally, the weights arguments are used if your samples are weighted in some way instead of each representing a sample with uniform probability.

**Comment by sg-s** [comment]
Thanks so much -- that clarifies things. I was feeding my probability densities into X and Y, which I see now is clearly wrong.
