### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by felix-russo** [garydoranjr/pyemd#9]
I have two samples of ~60 000 entries (i.e. numpy arrays of shape (60 000), and I always get a memory error when trying to calculate the emd... Is this normal? Can I fix this somehow?
Thanks a lot for your help!

**Comment by garydoranjr** [comment]
Hi @russofel, yes, I think is expected behavior but might be avoidable depending on your problem. I think the reason it's happening is that if you feed in samples that might be either vectors or scalars, the EMD code computes an n-by-n distance matrix between each of the samples that it uses to find the EMD between them. Since it uses 8-byte floating point numbers for this matrix, the size will be about 8*(60000^2) bytes or ~29 Gbytes, which I'm guessing is where the memory error occurs.

But if these samples are either 1-d or 2-d, you might be able to compute a histogram that summarizes the samples and then compute the EMD between the histograms. In this case, you would pass in the bin centers as the first two arguments, then the counts or probability mass of the histogram bins as the weights for the two samples. For 1-d samples, there is also [`scipy.stats.wasserstein_distance`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.wasserstein_distance.html) function that might be more efficient for that special case.

Let me know if that helps.

**Comment by felix-russo** [comment]
Hi @garydoranjr, thanks a lot for your quick response! Also, sorry for my late response, I had a lot of stuff to do for university, and I always hoped I would have the time to try your suggestion.
Sadly, the deadline for my project arrived to fast and I didn't manage to try it. Still, I talk a little about the EMD in my report and your implementation! 
Thanks a lot for your help!
